{{- if and .Values.haulerFileserver.enabled .Values.haulerFileserver.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hauler-fileserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hauler.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.haulerFileserver.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: hauler-fileserver
            port:
              number: {{ .Values.haulerFileserver.service.ports.targetPort }}
        path: /
        pathType: Prefix
  {{- if .Values.haulerFileserver.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.haulerFileserver.ingress.hostname }}
    secretName: {{ .Values.haulerFileserver.ingress.tls.secretName }}
  {{- end }}
{{- end }}
