{{- if and .Values.haulerRegistry.enabled .Values.haulerRegistry.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: hauler-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hauler.labels" . | nindent 4 }}
spec:
  selector:
    app: hauler-registry
  ports:
    - name: {{ .Values.haulerRegistry.service.ports.name }}
      protocol: {{ .Values.haulerRegistry.service.ports.protocol }}
      port: {{ .Values.haulerRegistry.service.ports.port }}
      targetPort: {{ .Values.haulerRegistry.service.ports.targetPort }}
  type: {{ .Values.haulerRegistry.service.type }}
{{- end }}
