# Helm Chart Values for Hauler
# Docs: https://hauler.dev

hauler:
  image:
    repository: ghcr.io/rancherfederal/hauler
    tag: v1.0.2
  imagePullPolicy: Always

  initContainers:
    image:
      repository: rancher/kubectl
      tag: v1.27.0 # update to your kubernetes version
    imagePullPolicy: Always
    timeout: 1h

  data:
    pvc:
      accessModes: ReadWriteMany
      storageClass: longhorn # optional... will use default storage class
      storageRequest: 48Gi # recommended size of 3x the artifact(s)

# Helm Chart Values for the Hauler Jobs
# Docs: https://rancherfederal.github.io/hauler-docs/docs/introduction/quickstart

haulerJobs:
  image:
    repository: rancher/shell
    tag: v0.1.22
  imagePullPolicy: Always

  hauls:
    enabled: true
    artifacts:
      - path: https://raw.githubusercontent.com/rancherfederal/hauler/main/testdata/haul.tar.zst
        name: haul.tar.zst
      # - path: /path/to/additional-hauls.tar.zst
      #   name: additional-hauls.tar.zst

  manifests:
    enabled: true
    artifacts:
      - path: https://raw.githubusercontent.com/rancherfederal/hauler/main/testdata/hauler-manifest.yaml
        name: hauler-manifest.yaml
      # - path: /path/to/additional-manifests.yaml
      #   name: additional-manifests.yaml

# Helm Chart Values for the Hauler Fileserver
# Docs: https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-fileserver

haulerFileserver:
  enabled: true
  port: 8080 # default port for the fileserver
  replicas: 1

  ingress:
    enabled: true
    hostname: fileserver.ranchers.io
    tls:
      enabled: true
      source: secret # only supported source
      secretName: tls-certs # must be created outside of this chart

  service:
    enabled: true
    type: ClusterIP
    ports:
      protocol: TCP
      port: 8080 # default port for the fileserver
      targetPort: 8080 # default port for the fileserver

# Helm Chart Values for the Hauler Registry
# Docs: https://rancherfederal.github.io/hauler-docs/docs/guides-references/command-line/hauler-store#hauler-store-serve-registry

haulerRegistry:
  enabled: true
  port: 5000 # default port for the registry
  replicas: 1

  ingress:
    enabled: true
    hostname: registry.ranchers.io
    tls:
      enabled: true
      source: secret # only supported source
      secretName: tls-certs # must be created outside of this chart

  service:
    enabled: true
    type: ClusterIP
    ports:
      protocol: TCP
      port: 5000 # default port for the registry
      targetPort: 5000 # default port for the registry
